# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf9b2b10f584a4f285ce1f2a31181a269b26efaa92be101a66870e6040cdd0b87e4bf33178e50dadb707eaf55a265ba80092d05145c64b645c4faa9f94926f7

test:
  secret_key_base: 5406168fad81ff9fafeb6de574e4a6029918063da2e31d2e8b5a07b9dfb2aaca99760ea23431951da57340b527c7440abd475f15eb0d500e1f5e92a5575a40c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
